/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@cain-group/cain-ui';


interface CaCheckboxGroupProps {
  
  /**  */
  disabled?: Components.CaCheckboxGroup["disabled"]
  
  /**  */
  min?: Components.CaCheckboxGroup["min"]
  
  /**  */
  max?: Components.CaCheckboxGroup["max"]
  
  /**  */
  size?: Components.CaCheckboxGroup["size"]
  
  /**  */
  value?: Components.CaCheckboxGroup["value"]
}

interface CaCheckboxGroupEvents {
  
}

interface CaCheckboxGroupSlots {
  default: any
}
  
/* generated by Svelte v3.47.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	flush,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let ca_checkbox_group;
	let current;
	const default_slot_template = /*#slots*/ ctx[8].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[7], null);

	return {
		c() {
			ca_checkbox_group = element("ca-checkbox-group");
			if (default_slot) default_slot.c();
			set_custom_element_data(ca_checkbox_group, "disabled", /*disabled*/ ctx[0]);
			set_custom_element_data(ca_checkbox_group, "min", /*min*/ ctx[1]);
			set_custom_element_data(ca_checkbox_group, "max", /*max*/ ctx[2]);
			set_custom_element_data(ca_checkbox_group, "size", /*size*/ ctx[3]);
			set_custom_element_data(ca_checkbox_group, "value", /*value*/ ctx[4]);
		},
		m(target, anchor) {
			insert(target, ca_checkbox_group, anchor);

			if (default_slot) {
				default_slot.m(ca_checkbox_group, null);
			}

			/*ca_checkbox_group_binding*/ ctx[9](ca_checkbox_group);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 128)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[7],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[7])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[7], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*disabled*/ 1) {
				set_custom_element_data(ca_checkbox_group, "disabled", /*disabled*/ ctx[0]);
			}

			if (!current || dirty & /*min*/ 2) {
				set_custom_element_data(ca_checkbox_group, "min", /*min*/ ctx[1]);
			}

			if (!current || dirty & /*max*/ 4) {
				set_custom_element_data(ca_checkbox_group, "max", /*max*/ ctx[2]);
			}

			if (!current || dirty & /*size*/ 8) {
				set_custom_element_data(ca_checkbox_group, "size", /*size*/ ctx[3]);
			}

			if (!current || dirty & /*value*/ 16) {
				set_custom_element_data(ca_checkbox_group, "value", /*value*/ ctx[4]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(ca_checkbox_group);
			if (default_slot) default_slot.d(detaching);
			/*ca_checkbox_group_binding*/ ctx[9](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { disabled = undefined } = $$props;
	let { min = undefined } = $$props;
	let { max = undefined } = $$props;
	let { size = undefined } = $$props;
	let { value = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(5, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function ca_checkbox_group_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(5, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('disabled' in $$props) $$invalidate(0, disabled = $$props.disabled);
		if ('min' in $$props) $$invalidate(1, min = $$props.min);
		if ('max' in $$props) $$invalidate(2, max = $$props.max);
		if ('size' in $$props) $$invalidate(3, size = $$props.size);
		if ('value' in $$props) $$invalidate(4, value = $$props.value);
		if ('$$scope' in $$props) $$invalidate(7, $$scope = $$props.$$scope);
	};

	return [
		disabled,
		min,
		max,
		size,
		value,
		__ref,
		getWebComponent,
		$$scope,
		slots,
		ca_checkbox_group_binding
	];
}

class CaCheckboxGroup extends SvelteComponent {
  $$prop_def: CaCheckboxGroupProps;
  $$events_def: CaCheckboxGroupEvents;
  $$slot_def: CaCheckboxGroupSlots;

  $on<K extends keyof CaCheckboxGroupEvents>(type: K, callback: (e: CaCheckboxGroupEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<CaCheckboxGroupProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			disabled: 0,
			min: 1,
			max: 2,
			size: 3,
			value: 4,
			getWebComponent: 6
		});
	}

	get disabled() {
		return this.$$.ctx[0];
	}

	set disabled(disabled) {
		this.$$set({ disabled });
		flush();
	}

	get min() {
		return this.$$.ctx[1];
	}

	set min(min) {
		this.$$set({ min });
		flush();
	}

	get max() {
		return this.$$.ctx[2];
	}

	set max(max) {
		this.$$set({ max });
		flush();
	}

	get size() {
		return this.$$.ctx[3];
	}

	set size(size) {
		this.$$set({ size });
		flush();
	}

	get value() {
		return this.$$.ctx[4];
	}

	set value(value) {
		this.$$set({ value });
		flush();
	}

	get getWebComponent(): HTMLCaCheckboxGroupElement | undefined {
		return this.$$.ctx[6];
	}
}

export default CaCheckboxGroup;