/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { Components, JSX } from '@cain-group/cain-ui';


interface CaFooterProps {
  
  /**  */
  height?: Components.CaFooter["height"]
}

interface CaFooterEvents {
  
}

interface CaFooterSlots {
  default: any
}
  
/* generated by Svelte v3.47.0 */
import {
	SvelteComponent,
	binding_callbacks,
	create_slot,
	detach,
	element,
	flush,
	get_all_dirty_from_scope,
	get_slot_changes,
	init,
	insert,
	safe_not_equal,
	set_custom_element_data,
	transition_in,
	transition_out,
	update_slot_base
} from "svelte/internal";

import { createEventDispatcher, onMount } from 'svelte';

function create_fragment(ctx) {
	let ca_footer;
	let current;
	const default_slot_template = /*#slots*/ ctx[4].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[3], null);

	return {
		c() {
			ca_footer = element("ca-footer");
			if (default_slot) default_slot.c();
			set_custom_element_data(ca_footer, "height", /*height*/ ctx[0]);
		},
		m(target, anchor) {
			insert(target, ca_footer, anchor);

			if (default_slot) {
				default_slot.m(ca_footer, null);
			}

			/*ca_footer_binding*/ ctx[5](ca_footer);
			current = true;
		},
		p(ctx, [dirty]) {
			if (default_slot) {
				if (default_slot.p && (!current || dirty & /*$$scope*/ 8)) {
					update_slot_base(
						default_slot,
						default_slot_template,
						ctx,
						/*$$scope*/ ctx[3],
						!current
						? get_all_dirty_from_scope(/*$$scope*/ ctx[3])
						: get_slot_changes(default_slot_template, /*$$scope*/ ctx[3], dirty, null),
						null
					);
				}
			}

			if (!current || dirty & /*height*/ 1) {
				set_custom_element_data(ca_footer, "height", /*height*/ ctx[0]);
			}
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(ca_footer);
			if (default_slot) default_slot.d(detaching);
			/*ca_footer_binding*/ ctx[5](null);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let __ref;
	let __mounted = false;
	const dispatch = createEventDispatcher();
	let { height = undefined } = $$props;
	const getWebComponent = () => __ref;

	onMount(() => {
		__mounted = true;
	});

	const setProp = (prop, value) => {
		if (__ref) $$invalidate(1, __ref[prop] = value, __ref);
	};

	const onEvent = e => {
		e.stopPropagation();
		dispatch(e.type, e.detail);
	};

	function ca_footer_binding($$value) {
		binding_callbacks[$$value ? 'unshift' : 'push'](() => {
			__ref = $$value;
			$$invalidate(1, __ref);
		});
	}

	$$self.$$set = $$props => {
		if ('height' in $$props) $$invalidate(0, height = $$props.height);
		if ('$$scope' in $$props) $$invalidate(3, $$scope = $$props.$$scope);
	};

	return [height, __ref, getWebComponent, $$scope, slots, ca_footer_binding];
}

class CaFooter extends SvelteComponent {
  $$prop_def: CaFooterProps;
  $$events_def: CaFooterEvents;
  $$slot_def: CaFooterSlots;

  $on<K extends keyof CaFooterEvents>(type: K, callback: (e: CaFooterEvents[K]) => any): () => void {
	  return super.$on(type, callback);
	}

  $set($$props: Partial<CaFooterProps>): void {
	  super.$set($$props);
	}

	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { height: 0, getWebComponent: 2 });
	}

	get height() {
		return this.$$.ctx[0];
	}

	set height(height) {
		this.$$set({ height });
		flush();
	}

	get getWebComponent(): HTMLCaFooterElement | undefined {
		return this.$$.ctx[2];
	}
}

export default CaFooter;