/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CaButton {
        "circle": boolean;
        "disabled": boolean;
        "loading": boolean;
        "plain": boolean;
        "round": boolean;
        "size": string;
        "type": string;
    }
    interface CaButtonGroup {
        "size": string;
        "type": string;
    }
    interface CaIcon {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLCaButtonElement extends Components.CaButton, HTMLStencilElement {
    }
    var HTMLCaButtonElement: {
        prototype: HTMLCaButtonElement;
        new (): HTMLCaButtonElement;
    };
    interface HTMLCaButtonGroupElement extends Components.CaButtonGroup, HTMLStencilElement {
    }
    var HTMLCaButtonGroupElement: {
        prototype: HTMLCaButtonGroupElement;
        new (): HTMLCaButtonGroupElement;
    };
    interface HTMLCaIconElement extends Components.CaIcon, HTMLStencilElement {
    }
    var HTMLCaIconElement: {
        prototype: HTMLCaIconElement;
        new (): HTMLCaIconElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ca-button": HTMLCaButtonElement;
        "ca-button-group": HTMLCaButtonGroupElement;
        "ca-icon": HTMLCaIconElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface CaButton {
        "circle"?: boolean;
        "disabled"?: boolean;
        "loading"?: boolean;
        "plain"?: boolean;
        "round"?: boolean;
        "size"?: string;
        "type"?: string;
    }
    interface CaButtonGroup {
        "size"?: string;
        "type"?: string;
    }
    interface CaIcon {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ca-button": CaButton;
        "ca-button-group": CaButtonGroup;
        "ca-icon": CaIcon;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ca-button": LocalJSX.CaButton & JSXBase.HTMLAttributes<HTMLCaButtonElement>;
            "ca-button-group": LocalJSX.CaButtonGroup & JSXBase.HTMLAttributes<HTMLCaButtonGroupElement>;
            "ca-icon": LocalJSX.CaIcon & JSXBase.HTMLAttributes<HTMLCaIconElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
